name: image_ink_well
description: Image InkWell Flutter plugin.
  This provides rectangle, rounded rectangle, circle type InkWell.
version: 0.1.0
author: Thomas Jeong<acadia3000@gmail.com>
homepage: https://github.com/acadia3000/image_ink_well

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
